#+title: Mortgage Markets
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>
#+PROPERTY: header-args    :exports none


Mortgages are loans collateralized by real property.  Mortgages are used in the purchase of most single family homes in the US.  Because the US has determined increased home ownership is in the public interest, Federal and State governments subsidize mortgage markets.

There is presently (march 2024) over 20 trillion of mortgage debt outstanding:

#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1iyjw&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export

The majority of which is 1-4 Family Residential Mortgages:

#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1iykn&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export

* Fixed-Rate Mortgages


* Agency and Government Sponsored Entity Mortgage Pools

#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1iyoj&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export

* Commercial Mortgages

The purchase or building of Commercial Properties (such as office buildings) can be financed through mortgages as well.  

#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1iykI&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export


* FRED Mortgage Data

[[https://fred.stlouisfed.org/tags/series?t=mortgage][All series matching "mortgage" are here.]]

** Delinquency

#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1hPP7&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export

* Mortgage Risk

If you own mortgages (own means you are the /lender/), there are generally 3 types of risk to your investment: (1) interest rate, (2) default and (3) prepayment risk.  We have previously covered interest rate and default risk, however prepayment risk is new and somewhat unique to mortgages.

** Interest Rate Risk


** Default Risk


** Prepayment Risk



* Mortgage Backed Securities

** CMOs

[[https://www.finra.org/finra-data/fixed-income/about-cmo-data][Data on CMOs are available from FINRA here.]]





