#+title: Mortgage Markets
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>
#+PROPERTY: header-args    :exports none


Mortgages are loans collateralized by real property.  Mortgages are used in the purchase of most single family homes in the US.  Because the US has determined increased home ownership is in the public interest, Federal and State governments subsidize mortgage markets.

There is presently (march 2024) over 20 trillion of mortgage debt outstanding:

#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1iyjw&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export

The majority of which is 1-4 Family Residential Mortgages:

#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1iykn&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export

* Fixed-Rate Mortgages


* Agency and Government Sponsored Entity Mortgage Pools

#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1iyoj&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export

* Commercial Mortgages

The purchase or building of Commercial Properties (such as office buildings) can be financed through mortgages as well.  

#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1iykI&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export


* FRED Mortgage Data

[[https://fred.stlouisfed.org/tags/series?t=mortgage][All series matching "mortgage" are here.]]

** Delinquency

#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1hPP7&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export


#+begin_quote
**Extra Credit:** Does credit card delinquency precede mortgage delinquency?  Pull data from FRED and test.
#+end_quote


* Mortgage Risk

If you own mortgages (own means you are the /lender/), there are generally 3 types of risk to your investment: (1) interest rate, (2) default and (3) prepayment risk.  We have previously covered interest rate and default risk, however prepayment risk is new and somewhat unique to mortgages.

** Interest Rate Risk


** Default Risk


** Prepayment Risk



* Mortgage Backed Securities (MBS)

** Example MBS

** Collateralized Mortgage Obligations (CMOs)

Say we have a MBS with an expected overall 10% default rate.  Roughly, for every $10 in principal invested in the security, you expect to lost $1 due to default.  This default rate is fairly high.

However, what if we split this MBS into /tranches/.  The first tranche (tranche A) receives all principal payments until they are repaid their full principal.  Let's say each tranche is 20% of the CMO.  Then for A to not receive its principal in full, more than 80% of the mortgages underlying the CMO must default.  So A is very safe.

Once tranche A is paid, all principal payments will flow to tranche B.  Once B is paid payments flow to tranche C, D, and finally Z (the last tranche is known as the Z-tranche).  In terms of default risk, tranche B is also very safe, C a bit more risky, down to tranche Z which is very risky.  In fact, we expect 50% of Z-tranche to default.
 
Taking a step back, what the CMO has allowed us to do is take a pool of mortgages with moderate risk, and transform this into a set of securities, some of which are very safe, and some very risky.  We do this because investors have different risk preferences---some may want very safe securities and some may want risky (high return) securities.  Thus, we can target investor preferences.

** Interest-Only/Principal-Only

CMOs can also be stripped into interest-only (IO) or principal-only (PO) securities.  IO securities only receive interest payments, and POs only principal.  Remember standard fixed-rate mortgage payments are part interest and part principal.

IO/PO CMOs are an important tool for banks to manage /prepayment risk/.  Let's say you are exposed to prepayment risk, which means if interest rates decline you will receive the funds you lent back in a lower interest rate environment.  So you want to buy a security that increases in value if prepayments increase.  You can then buy a PO security---if prepayments increase the PO receives its money earlier which increases its value.

[[https://www.finra.org/finra-data/fixed-income/about-cmo-data][Data on CMOs are available from FINRA here.]]


* Securitization

[[https://matt-brigida.github.io/securitization-presentation-abridged/][See this presentation on securitization.]]  Note, the presentation navigates both to the right and down.
